### ISSUE TITLE
`subctl show brokers` not actually showing any useful information

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/subctl#115]
**What happened**:
I run `subctl show brokers` and get nothing useful.
```sh
# subctl show brokers
Cluster "cluster1"
 ✓ Detecting broker(s)
NAMESPACE                NAME                     COMPONENTS                              
submariner-k8s-broker    submariner-broker        service-discovery, connectivity         

Cluster "cluster2"
 ✓ Detecting broker(s)
```

**What you expected to happen**:
At least the spec from the defined broker should be shown (perhaps not in yaml), ie:
```yaml
Spec:
  Components:
    service-discovery
    connectivity
  Default Globalnet Cluster Size:  65536
  Globalnet CIDR Range:            242.0.0.0/8
  Globalnet Enabled:               true
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Im not sure if this is a bug or an enhancement :)
I think we could regard this as a bug, since `subctl show brokers` should give some useful info besides the fact where broker is installed.

FWIW I don't think extended info should be shown in `subctl show all` but we could debate that.

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:
