### ISSUE TITLE
Add more detail to subctl diagnose connections

### ISSUE THREAD

**Issue by skitt** [submariner-io/subctl#230]
`subctl diagnose connections` reports the current status of the various connections, but that’s not sufficient information when then connections aren’t established. It would be useful if, in the absence of connections, `diagnose connections` could perform tests in the same vein as the firewall tests:

* spawn a pod in each cluster and attempt to connect to the other clusters, reporting the addresses it’s trying to use
* when traffic is successfully received, report the source IP addresses too

This would be helpful to identify mismatched NAT configurations or incorrectly-detected public IP addresses.

**Comment by sridhargaddam** [comment]
Currently, `subctl diagnose connections` is executed on a single cluster (taking kubeconfig of local cluster) and reports the status of connections on the Gateway node of the cluster.

If we want to enhance it as described in this issue, we will require kubeconfigs of multiple clusters similar to `firewall inter-cluster ...` command. Shall we rather enhance `subctl diagnose firewall nat-discovery ...` instead?

```
Usage:
  subctl diagnose firewall [command]

Available Commands:
  inter-cluster Check firewall access to setup tunnels between the Gateway node
  intra-cluster Check firewall access for intra-cluster Submariner VxLAN traffic
  metrics       Check firewall access to metrics
  nat-discovery Check firewall access for nat-discovery to function properly
```

**Comment by skitt** [comment]
Putting this in the `firewall` command suggests that it’s firewall-related, which it isn’t really. (Firewall issues can cause the connections problems we’re trying to diagnose, but they’re not the only possible cause.)

To avoid changing the current `subctl diagnose connections` requirements, I’d rather have it so that if `subctl diagnose connections` reports failed connections (of any kind, _i.e._ any situation where connections aren’t established), it suggests running another command to investigate further. That command could even be `subctl diagnose connections` again but with an additional parameter giving the kubeconfigs and/or contexts required to access other clusters (and if those were passed initially, there wouldn’t be a separate step).

**Comment by sridhargaddam** [comment]
> * spawn a pod in each cluster and attempt to connect to the other clusters, reporting the addresses it’s trying to use
> * when traffic is successfully received, report the source IP addresses too

The Auto-NAT discovery code does pretty much the same and updates the `gateways.submariner.io` object with `usingIP` which informs us the ip-address that was reachable. The auto-NAT discovery code is now stable and if it fails, my main suspicion would be on the firewall configuration. 

> This would be helpful to identify mismatched NAT configurations

By mismatched NAT configuration do you mean a user configuring a wrong value for (--natt) which does not match with the setup? But again this flag is referred to only when Auto-NAT discovery fails. Are you suggesting that as part of diagnose connections, we perform auto-nat discovery and check if it matches with "--natt" setting?

>  or incorrectly-detected public IP addresses.

As you know, the public-ip detection currently is automated. With incorrectly detected public-ip do you mean user labelling an invalid public-ip on the Gateway node which does not match with the real public-ip?


```
  status:                                                                                                                                                                         
    connections:                                                                                                                                                                             
    - endpoint:                                                                                                                                                                              
        backend: libreswan                                                                                                                                                                   
        backend_config:                                                                                                                                                                      
          natt-discovery-port: "4490"                                                                                                                                                        
          preferred-server: "false"
          udp-port: "4500"
        cable_name: submariner-cable-cluster2-172-18-0-7
        cluster_id: cluster2
        healthCheckIP: 10.130.0.2
        hostname: cluster2-worker
        nat_enabled: false
        private_ip: 172.18.0.7
        public_ip: 103.224.36.132
        subnets:
        - 100.66.0.0/16
        - 10.130.0.0/16
      latencyRTT:
        average: 511.303µs
        last: 563.691µs
        max: 8.613526ms
        min: 132.841µs
        stdDev: 174.477µs
      status: connected
      statusMessage: ""
      usingIP: 172.18.0.7          ----------> This one.
    haStatus: active
```
