### ISSUE TITLE
cluster-role does not have daemonset permissions

### ISSUE THREAD

**Issue by Hewie8023** [submariner-io/subctl#561]
**What happened**:
When I use subctl version 0.14 to join the cluster, after the join is successful, I found the following error in the logs of submariner operation

```
error="error discoverying cluster network: error listing the Daemosets: daemonsets.apps is forbidden: User \"systen:serviceaccount:submariner-operator\" cannot list resource \"daemonsets\" in API group \"apps\" in the namespace \"kube-sustem\""
```

**What you expected to happen**:
no error

**How to reproduce it (as minimally and precisely as possible)**:
`subctl join `

**Anything else we need to know?**:
I manually added the following information in Config_rbac_submariner_operator_cluster_role_yaml: 
```
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
```

It can be executed normally, is it lack of permissions?

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:
