### ISSUE TITLE
write krew manifest file for subctl

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/subctl#838]
write a crew manifest file for subctl so that subctl can be installed via Krew. The file needs to be submitted to [krew index](https://github.com/kubernetes-sigs/krew-index/tree/master/plugins) after 0.16.0 release.

The manifest file would look like this:

```
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: subm
spec:
  version: "v0.16.0"
  homepage: https://github.com/submariner-io/subctl
  shortDescription: "Manages Submariner and its services"
  description: |
    CLI to install, uninstall and troubleshoot Submariner on a Kubernetes cluster.
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/submariner-io/releases/releases/download/v0.15.0/subctl-v0.15.0-linux-amd64.tar.gz
      sha256: "e5a1ee20019a345a45cb3dcd4f653ea9eb0e34c04f6b6e598bf1294e37359095"
      files:
        - from: subctl*/subctl
          to: .
      bin: subctl
```

Changes to be made:
1. The URL has to be changed
2. Logic for other OS/Arch needs to be added

Depends on: https://github.com/submariner-io/releases/issues/723
